### ISSUE TITLE
Requesting new version

### ISSUE THREAD

**Issue by ImportTaste** [suntong/html2md#18]
html-to-markdown just updated with a feature/bug I requested/reported, the use of the start attribute: https://github.com/JohannesKaufmann/html-to-markdown/releases/tag/v1.5.0

**Comment by suntong** [comment]
https://github.com/suntong/html2md/releases/tag/v1.1.2 should be built with the latest html-to-markdown release. Please double-check and let me know. thx.

**Comment by suntong** [comment]
Hmm... one sec, does such updated feature need a cli change? 
If so, what do you propose?

**Comment by suntong** [comment]
Ok. closing it then.
