### ISSUE TITLE
Rebuild please

### ISSUE THREAD

**Issue by vivook** [suntong/html2md#4]
Hi,

Since this doesn't use go modules I can't work out how to build it locally.

Please can you trigger a rebuild since html-to-markdown is now on 1.3.4 as of today.

Thanks

**Comment by suntong** [comment]
Closed as completed via [f584bf7](https://github.com/suntong/html2md/commit/f584bf775faa77901bac27e1ab3416c4712544e8).

**Comment by suntong** [comment]
@all-contributors please add @vivook  for bug, userTesting
