### ISSUE TITLE
Excluding by a selector?

### ISSUE THREAD

**Issue by 097115** [suntong/html2md#6]
Including only text inside the specified selector is extremely handy, no doubts about it. But what if inside this text still there's a block (like an ad, for instance), which we'd like to **exclude**, to drop? Right now it's not possible, I understand?

**Comment by suntong** [comment]
Sorry I had the wrong notice setting and was only able to notice your issue just now. 

Indeed, excluding selector is not possible, I'll think about it...

**Comment by suntong** [comment]
@all-contributors please add @097115  for bug, ideas, userTesting
